### ISSUE TITLE
add months needed for spring and winter run in year 2000

### ISSUE THREAD

**Issue by ergz** [CVPIA-OSC/DSMflow#5]
we need months 1-5 of the year 2000

**Comment by ErinCain** [comment]
Rda that need 2020 added 
- [ ]  cvp_exports.rda 
- [ ]  delta_inflow.rda
- [ ]  freeport_flows.rda
- [ ]  stockton_flow.rda
- [ ]  swp_exports.rda 
- [ ]  vernalis_flow.rda

Other rdas in package that already have 2000 or do not depend on it. 
- [ ]  bypass_flows.rda (already goes until 2002) 
- [ ]  delta_cross_channel_closed.rda (Does not vary by year) 
- [ ]  delta_flows (already goes until 2002) 
- [ ]  delta_proportion_diverted  (already includes 2000) 
- [ ]  delta_total_diverted (already includes 2000) 
- [ ]  flows_cds.rda (already goes until 2002) 
- [ ]  gates_overtopped (already includes 2000)
- [ ]  mean_flow.rda (already includes 2000) 
- [ ]  proportion_diverted.rda (already includes 2000) 
- [ ]  total_diverted.rda (already includes 2000) 
- [ ]  proportion_flow_bypasses (already includes 2000) 
- [ ]  proportion_flow_natal (already includes 2000) 
- [ ]  proportion_pulse_flows (does not vary by year) 
- [ ]  uppper_sacramento_flows.rda (already includes 2000)
